-- DELETE FROM directorFilm;
-- DELETE FROM directors;
-- DELETE FROM films;
-- DELETE FROM users;
-- DELETE FROM film_genre;
DELETE FROM genre;
-- DELETE FROM likesList;
-- DELETE FROM friendship;
DELETE FROM mpa;
-- DELETE FROM friendshipStatus;
-- DELETE FROM events;
INSERT INTO genre (genreId, name) VALUES (1, 'Комедия');
INSERT INTO genre (genreId, name) VALUES (2, 'Драма');
INSERT INTO genre (genreId, name) VALUES (3, 'Мультфильм');
INSERT INTO genre (genreId, name) VALUES (4, 'Триллер');
INSERT INTO genre (genreId, name) VALUES (5, 'Документальный');
INSERT INTO genre (genreId, name) VALUES (6, 'Боевик');
INSERT INTO mpa (mpaId, name) VALUES(1, 'G');
INSERT INTO mpa (mpaId, name) VALUES(2, 'PG');
INSERT INTO mpa (mpaId, name) VALUES(3, 'PG-13');
INSERT INTO mpa (mpaId, name) VALUES(4, 'R');
INSERT INTO mpa (mpaId, name) VALUES(5, 'NC-17');
INSERT INTO friendshipStatus (friendshipStatusId, description) VALUES (1, 'apply');
INSERT INTO friendshipStatus (friendshipStatusId, description) VALUES (2, 'not apply');